### ISSUE TITLE
Unable to add to Tag Manager

### ISSUE THREAD

**Issue by footsteps-design** [gtm-server/mailchimp-tag#1]
I can find it in the community template gallery

https://tagmanager.google.com/gallery/#/owners/stape-io/templates/mailchimp-tag

And the add to workspace button says:

To use this template in your workspace, open Tag Manager, find this template in Templates > Search Gallery and add it to your workspace.

However when I try going to Templates and then Search Gallery I can't find it as a search result.

I hope I'm doing something wrong, or it's an easy fix.

Thanks

**Comment by Bukashk0zzz** [comment]
Are you trying to add this template to the Server Side GTM?

**Comment by footsteps-design** [comment]
Thank you for your quick response.

Clearly I need to read the documentation better.

I've now been able to add it to the Server container successfully.

Thanks :)
