### ISSUE TITLE
The display name should follow the format: [Company Name] [Tag Name]

### ISSUE THREAD

**Issue by opozo** [gtm-server/mailchimp-tag#5]
The current display name is as follows:

Display Name: Mailchimp

The display name should follow the format: [Company Name] [Tag Name].

**Comment by Bukashk0zzz** [comment]
Thanks for the issue.
This fixed in https://github.com/stape-io/mailchimp-tag/commit/26e19327dc73a3f1b692dab31d02a678e19b4b1c
