### ISSUE TITLE
 Use encodeUri() if part of the URL path

### ISSUE THREAD

**Issue by opozo** [gtm-server/mailchimp-tag#7]
When reviewing your template we've noticed that it is using user-defined parameters to build a URL. It's best practice to use [encodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path [[1](https://github.com/stape-io/mailchimp-tag/blob/44d864bac7f051cfba66e1a07f33c54f0877b263/template.tpl#L254)] [[2](https://github.com/stape-io/mailchimp-tag/blob/44d864bac7f051cfba66e1a07f33c54f0877b263/template.tpl#L316)].

**Comment by Bukashk0zzz** [comment]
Thanks for the issue.
This fixed in https://github.com/stape-io/mailchimp-tag/commit/26e19327dc73a3f1b692dab31d02a678e19b4b1c
